name: qnotes_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  rxdart: ^0.27.7
  permission_handler: ^10.0.1
  json_annotation: ^4.3.0
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  get_it: ^7.6.0
  go_router: ^10.0.0
  flutter_secure_storage: ^8.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  path: ^1.8.2
  platform_device_id: ^1.0.1
  flutter_easyloading: ^3.0.5
  photo_manager: ^2.8.1
  flutter_persistent_keyboard_height: ^1.0.5
  device_info_plus: ^9.0.2
  jiffy: ^6.2.1
  flutter_dotenv: ^5.1.0
  video_player: ^2.7.2
  image_picker: ^1.0.5
  flutter_local_notifications: ^16.3.0
  url_launcher: ^6.1.14
  loadmore: ^2.1.0
  uuid: ^4.2.2
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/
